cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --account={resources.account}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.time}
    --ntasks={resources.ntasks}
default-resources:
  - mem_mb=6000
  - account=PAS2276
  - time="04:00:00"
  - ntasks=1
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 120
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
