cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --nodes={resources.nodes}
    --parsable
    --partition={resources.partition}
    --cpus-per-task={threads}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --account=PAS2276
    --time={resources.time}
    --mem={resources.mem_mb}
default-resources:
  - partition=serial
  - time="2:00:00"
#restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
#use-conda: True
#conda-frontend: conda
cluster-status: status-sacct.sh
